### ISSUE TITLE
Doesn't show artist or album name on Apple Music

### ISSUE THREAD

**Issue by Hafumoto** [keifufu/WebNowPlaying-Rainmeter#10]
I constantly get "N/A" on everything from Apple Music on artist names and album names.

**Comment by keifufu** [comment]
If on Firefox, make sure the extension has permission on the page.
And just to make sure, you are using the web page right?

**Comment by Hafumoto** [comment]
I was running the Windows Preview app. Tried it in the browser, but it didn't work at all. Allowed it to run in private windows and then it worked, showing all info.

Will it be fixed for the app as well as some point, seeing as it shows some info from the app, but not all?

**Comment by keifufu** [comment]
Desktop players are only supported if they can report their media info to Windows, eg: show up in the volume flyout or media control center.
If apple music does not have this built-in, you'll have to hope they add it (since it's apple I doubt it though).

**Comment by Hafumoto** [comment]
> Desktop players are only supported if they can report their media info to Windows, eg: show up in the volume flyout or media control center. If apple music does not have this built-in, you'll have to hope they add it (since it's apple I doubt it though).

It does though. I just tested it, and the entire info show up in the [action center](https://imgur.com/mgPsL3o).

**Comment by keifufu** [comment]
In that case, just make sure you're on plugin version 2.0.1 or newer

**Comment by Hafumoto** [comment]
I'm on browser plugin 2.0.4 (Firefox) and Rainmeter 2.0.5.

**Comment by keifufu** [comment]
Unless you disabled "use native apis" in the extension settings, rm2.0.5 should pick up everything from the action center.

**Comment by Hafumoto** [comment]
Without "Use native APIs", I'm not getting any info. I have no idea why it only picks up song title and album art.

**Comment by keifufu** [comment]
this is likely to be fixed in the next update

**Comment by lightningcal** [comment]
Using the latest release 2.0.7 and chrome browser extension. From desktop Apple Music app, on Windows 10, i'm not seeing artist or album name either.

![image](https://github.com/user-attachments/assets/b942e237-7b2d-4cb4-886f-ca930bcce831)

**Comment by keifufu** [comment]
still fixed in next update (there has not been one yet, no clue when I'll get around to it)

**Comment by keifufu** [comment]
Should be fixed in a pre-release now. I do not recommend using it until it becomes stable though.
