### ISSUE TITLE
Spotify rating not working

### ISSUE THREAD

**Issue by lightwithin** [keifufu/WebNowPlaying-Rainmeter#17]
Spotify rating seems to have stopped working recently.  I assume change on Spotify's end broke it?

**Comment by keifufu** [comment]
Depends, if you're talking about the website then I will have an update to fix it within the next few months, whenever i have the rest of the stuff I'm working on done.

If you mean the desktop player however, read: https://wnp.keifufu.dev/desktop-players#caveats
