### ISSUE TITLE
YoutubeMusic Volume

### ISSUE THREAD

**Issue by Shak404** [keifufu/WebNowPlaying-Rainmeter#18]
First of all, I'm a newb. I barely know what I'm doing.

Regardless, I still managed to put together a very simple player that looks and does exactly like I want by starting from the Rainmeter example provided. I exclusively use it for the browser version of YTM (https://music.youtube.com).

There's just one thing that's not working and that I would like to fix, if possible:

```
[MeasureVolume]
Measure=Plugin
Plugin=WebNowPlaying
PlayerType=Volume
Substitute="":"N/A"

[MeterVolProgressBar]
Meter=Bar
MeasureName=MeasureVolume
X=580
Y=7
W=7
H=42
BarColor=255,255,255,255
SolidColor=125,125,125,128
BarOrientation=Vertical
LeftMouseUpAction=[!CommandMeasure MeasureVolume "SetVolume 100-$MouseY:%$"]

[MeterVolumeDebug]
Meter=String
x=570
y=55
FontColor=255,255,255,255
Group=DynamicColors
MeasureName=MeasureVolume
```

It seems that I'm unable to get the MeasureVolume to work properly. It always output 100 regardless. Even when using the bar to change it 'manually', it will revert back to 100 on the next tick. I also tried a more straightforward SetVolume +5 like in the original example but that gave the same results.
Changing the volume inside the browser also does not affect the player Volume at all.

Maybe I'm missing something. Maybe it's just not something that,s possible with YTM. Either way, I don't really know where else to ask so I'm hoping someone here can help me shed some light on this issue.

![image_2023-10-30_221809200](https://github.com/keifufu/WebNowPlaying-Rainmeter/assets/95598662/5881062e-3c9a-4c2f-a774-93a9f68bbf8d)

**Comment by keifufu** [comment]
Do you have the browser extension installed?
By "it will revert back to 100 on the next tick" do you mean the volume in rainmeter will revert, or that the YTM volume is stuck?

**Comment by Shak404** [comment]
Yes I do have the extension installed.

I mean the volume in rainmeter. I can still play with the volume from the website itself, but the widget will always show like it's at full volume. like it's not picking up the volume value properly from youtube music.

Also, I just tested and:
It does however pick up the volume from Youtube itself. and it does adjust the bar according to what I adjust the youtube video  volume to be.
there's an issue if I try the other way around: if I change the volume from the the widget by clicking on the bar it doesnt adjust properly and only bring the volume down. But that might very well be an error on my part in the widget code.

**Comment by keifufu** [comment]
Well I do know that the current extension does not read YouTube volume correctly, I'm not sure about ytm though. I have that fixed on a local version which I don't want to release yet so maybe I'll just backport the volume fixes later.

**Comment by Shak404** [comment]
Alright well, I'll fiddle on my end, but let me know if I can provide any info that could also help you look as to why ytm is not working at all.

**Comment by Shak404** [comment]
Just to let you know that I've managed to make the volume slider work as expected for Youtube itself.
but the YoutubeMusic is still a no go.
again, If I can provide any kind of information to help you find what might be causing the issue, do not hesitate.

**Comment by keifufu** [comment]
I'm still unable to replicate this, are you perhaps also experiencing [this issue](https://github.com/keifufu/WebNowPlaying/issues/29)?

**Comment by keifufu** [comment]
Not a rainmeter plugin issue regardless, open an issue on [keifufu/WebNowPlaying](https://github.com/keifufu/WebNowPlaying) instead if you still experience this issue.
