### ISSUE TITLE
Add support for PlexAMP

### ISSUE THREAD

**Issue by FloydianSound** [keifufu/WebNowPlaying-Rainmeter#20]
Hello
i love your skin and been using it for over a year now !

i would really like to see an implementation of PLEX with the AudioMeter Gadget.

It should be easy enough, using the webservice from your latest update i can see the plex icon loading in, but the songs do not get picked up from PLEXAmp

possibly a simple fix, or maybe thinking into making a PLEX native Plug-in to tap into ?

**Comment by FloydianSound** [comment]
After further testing, regular Plex App from the microsoft store does work with the plug-in

not sur why PlexAmp does not....

**Comment by keifufu** [comment]
Desktop players are supported as long as they report to the windows API responsible for showing and controlling media in the win10 volume popup or the win11 media control center. There is nothing I can do if these apps don't implement good support for it, if at all.

**Comment by keifufu** [comment]
I'll leave a link to the relevant Microsoft documentation for this feature here.
Feel free to continue responding here if needed, just going to close this as this is not something I can fix in WebNowPlaying.

https://learn.microsoft.com/en-us/uwp/api/windows.media.control.globalsystemmediatransportcontrolssessionmanager
