### ISSUE TITLE
Get artist

### ISSUE THREAD

**Issue by long18020851** [keifufu/WebNowPlaying-Rainmeter#22]
When I resume listening to the unfinished song after opening Spotify, I can't get the artist's name. I can get all other measures except artist.

**Comment by keifufu** [comment]
Is no artist being reported at all? Spotify only reports the first artist to Windows, so it's expected to only report the first artist.

**Comment by long18020851** [comment]
No artist at all. Even if the song has one or more than one artist.

**Comment by long18020851** [comment]
![Screenshot 2024-06-08 173733](https://github.com/keifufu/WebNowPlaying-Rainmeter/assets/56619821/e178c5b8-6398-48b3-abd0-7754c280de02)

**Comment by keifufu** [comment]
Is this with the Spotify desktop app or the web player?

**Comment by long18020851** [comment]
spotify desktop

**Comment by keifufu** [comment]
The Windows 11 Media Control thingie (when clicking on audio in the taskbar) also fails to report the artist until the song changes, so I assume Spotify (or Windows itself) fails to report correctly.
