### ISSUE TITLE
MusicBee WebNowPlugin

### ISSUE THREAD

**Issue by Mojas84** [keifufu/WebNowPlaying-Rainmeter#23]
Hi we can please create plugin for MusicBee Player??? Work with overlay Win10 plugin but without cover art........

**Comment by Mojas84** [comment]
![sshot-2](https://github.com/keifufu/WebNowPlaying-Rainmeter/assets/108186899/8a9755af-716e-472a-a8d2-dad959ca3785)

**Comment by keifufu** [comment]
Nothing I can do if MusicBee does not integrate with Windows properly. Report this upstream please.
