### ISSUE TITLE
The rainmeter player didn't show anything after a boot from sleepmode

### ISSUE THREAD

**Issue by AnsonVTo** [keifufu/WebNowPlaying-Rainmeter#26]
Hi, I find out that if I use Edge with the chrome extension, my rainmeter skin (SquarePlayer) won't showup anything after I wake my computer up in sleep mode unless I restart the Edge browser. However, I tested that if I use Chrome instead of Edge, it works, it is pretty strange. I just curious is there any solusion for this?

**Comment by keifufu** [comment]
I have no clue.

**Comment by AnsonVTo** [comment]
Nvm, I just notice that refreshing the page and it is go to go haha
