### ISSUE TITLE
Rainmeter + Spicetify

### ISSUE THREAD

**Issue by lmaoNebula** [keifufu/WebNowPlaying-Rainmeter#27]
I've been using spicetify for a while and I have the WebNowPlaying extension which in theory should work alongside rainmeter. I am using mond, but the 2 don't work together. I would think that spotify/spicetify isn't working with rainmeter, but the example skin actually works, its just mond.

**Comment by keifufu** [comment]
mond does not support webnowplaying, either manually edit all instances of `Plugin=NowPlaying` to `Plugin=WebNowPlaying` or use [mondtholomew](https://mondtholomew.rainmeter.skin/)
