### ISSUE TITLE
Media info is cleared momentarily on song change

### ISSUE THREAD

**Issue by dethknite** [keifufu/WebNowPlaying-Rainmeter#28]
Not a bug necessarily.
During latest v3.0.0.0 beta 3 testing, I noticed in Youtube Music Player that when skipping to next / prev song, the Artist, Song, Cover, and info are all reset momentarily.  Seems to be "0" for Artist / Title.

This may be intentional, though it does cause some issues with the auto-hide features of some skins (sometimes they go to 0 and then hide, then come back on the next UpdateMeasure).

**Comment by keifufu** [comment]
Since this is already a week old, are you sure your extension was on v3.1.0? I published it to the webstores just about a week ago and chrome takes its sweet time to update.

**Comment by dethknite** [comment]
Yes. I did go ahead and try with the v3.0.0.0 beta 4 skin.. v3.1.0 browser addon, which still exhibits this behavior. When it occurs, (sometimes during a move to next/prev -- likely dependent upon the UpdateMeasure occuring during this change song), the "Active" text is cleared, and the "1" becomes "0" until the next UpdateMeasure.

**Comment by keifufu** [comment]
Thanks, I'll make sure this is fixed before the actual v3 release. Please note that the alpha's were accidentally picked up as an update by the browser extension before v3.1.0 and were not really meant to be updated to from 2.0.7 (stable).

**Comment by dethknite** [comment]
Thanks for pointing that out. I removed the web addon and reinstalled it. Also allowed it the extra permissions. Monstercat skin no longer loses detection of media playing (though the Artist does occasionally still goes to 0 till update). That is okay with me though... as long as skins are not reloading... this seems more responsive than the older plugin. *cheers*
